'use client'

import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import {
  GitBranch, CheckCircle2, Clock, DollarSign, Filter, Users,
} from 'lucide-react'

interface ReferralRow {
  id: string
  referral_code: string | null
  status: string
  commission_amount: number | null
  paid_at: string | null
  created_at: string
  referred_customer_id: string | null
}

interface Props {
  referrals: ReferralRow[]
}

type FilterType = 'all' | 'pending' | 'converted' | 'paid'

const STATUS_CONFIG: Record<string, { label: string; color: string }> = {
  pending:         { label: 'Pending',       color: '#f59e0b' },
  click:           { label: 'Click',         color: '#9299b5' },
  converted:       { label: 'Converted',     color: '#22c07a' },
  paid:            { label: 'Paid Out',      color: '#8b5cf6' },
  pending_payout:  { label: 'Payout Req',    color: '#22d3ee' },
}

const fmt = (n: number) =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n)

const fmtDate = (d: string) =>
  new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })

function StatusPill({ status }: { status: string }) {
  const cfg = STATUS_CONFIG[status] || { label: status, color: '#9299b5' }
  return (
    <span style={{
      display: 'inline-flex',
      alignItems: 'center',
      padding: '2px 10px',
      borderRadius: 6,
      fontSize: 10,
      fontWeight: 800,
      textTransform: 'uppercase',
      letterSpacing: '0.06em',
      color: cfg.color,
      background: `${cfg.color}18`,
    }}>
      {cfg.label}
    </span>
  )
}

export default function AllReferralsClient({ referrals: initial }: Props) {
  const [referrals, setReferrals] = useState<ReferralRow[]>(initial)
  const [filter, setFilter] = useState<FilterType>('all')
  const [updating, setUpdating] = useState<string | null>(null)
  const supabase = createClient()

  const filtered = referrals.filter(r => {
    if (filter === 'all') return true
    if (filter === 'pending') return r.status === 'pending' || r.status === 'click'
    if (filter === 'converted') return r.status === 'converted' || r.status === 'pending_payout'
    if (filter === 'paid') return r.status === 'paid'
    return true
  })

  const totalOwed = referrals
    .filter(r => r.status === 'converted' || r.status === 'pending_payout')
    .reduce((s, r) => s + (r.commission_amount || 0), 0)

  const totalPaid = referrals
    .filter(r => r.status === 'paid')
    .reduce((s, r) => s + (r.commission_amount || 0), 0)

  const handleMarkPaid = async (id: string) => {
    setUpdating(id)
    await supabase.from('referral_tracking').update({ status: 'paid', paid_at: new Date().toISOString() }).eq('id', id)
    setReferrals(prev => prev.map(r => r.id === id ? { ...r, status: 'paid', paid_at: new Date().toISOString() } : r))
    setUpdating(null)
  }

  const FILTERS: { key: FilterType; label: string; count: number }[] = [
    { key: 'all',       label: 'All',       count: referrals.length },
    { key: 'pending',   label: 'Pending',   count: referrals.filter(r => r.status === 'pending' || r.status === 'click').length },
    { key: 'converted', label: 'Converted', count: referrals.filter(r => r.status === 'converted' || r.status === 'pending_payout').length },
    { key: 'paid',      label: 'Paid Out',  count: referrals.filter(r => r.status === 'paid').length },
  ]

  return (
    <div>
      {/* ─── Header ─────────────────────────────────────────────────── */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 }}>
        <div>
          <div style={{
            fontFamily: 'Barlow Condensed, sans-serif',
            fontSize: 26, fontWeight: 900, color: 'var(--text1)',
            display: 'flex', alignItems: 'center', gap: 8,
          }}>
            <GitBranch size={22} /> Customer Referrals
          </div>
          <div style={{ fontSize: 12, color: 'var(--text3)', marginTop: 2 }}>
            All referrals generated by the customer portal referral program
          </div>
        </div>
      </div>

      {/* ─── Stats ──────────────────────────────────────────────────── */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12, marginBottom: 24 }}>
        {[
          { label: 'Total Referrals', value: String(referrals.length), icon: Users, color: 'var(--accent)' },
          { label: 'Credits Owed',    value: fmt(totalOwed),           icon: Clock, color: 'var(--amber)' },
          { label: 'Total Paid Out',  value: fmt(totalPaid),           icon: CheckCircle2, color: 'var(--green)' },
        ].map(stat => (
          <div key={stat.label} style={{
            padding: '16px 20px',
            background: 'var(--surface)',
            border: '1px solid var(--border)',
            borderRadius: 12,
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}>
              <stat.icon size={14} style={{ color: stat.color }} />
              <span style={{ fontSize: 10, fontWeight: 800, color: 'var(--text3)', textTransform: 'uppercase', letterSpacing: '0.07em' }}>
                {stat.label}
              </span>
            </div>
            <div style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 22, fontWeight: 800, color: stat.color }}>
              {stat.value}
            </div>
          </div>
        ))}
      </div>

      {/* ─── Filter tabs ────────────────────────────────────────────── */}
      <div style={{ display: 'flex', gap: 6, marginBottom: 16 }}>
        {FILTERS.map(f => (
          <button
            key={f.key}
            onClick={() => setFilter(f.key)}
            style={{
              padding: '6px 14px',
              borderRadius: 8,
              border: `1px solid ${filter === f.key ? 'var(--accent)' : 'var(--border)'}`,
              background: filter === f.key ? 'rgba(79,127,255,0.1)' : 'transparent',
              color: filter === f.key ? 'var(--accent)' : 'var(--text2)',
              fontSize: 12, fontWeight: 700, cursor: 'pointer',
              display: 'flex', alignItems: 'center', gap: 6,
            }}
          >
            <Filter size={12} />
            {f.label}
            <span style={{
              padding: '0 6px', borderRadius: 10, fontSize: 10,
              background: filter === f.key ? 'rgba(79,127,255,0.2)' : 'var(--surface2)',
              color: filter === f.key ? 'var(--accent)' : 'var(--text3)',
            }}>
              {f.count}
            </span>
          </button>
        ))}
      </div>

      {/* ─── Table ──────────────────────────────────────────────────── */}
      {filtered.length === 0 ? (
        <div style={{
          textAlign: 'center', padding: 48,
          background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12,
          color: 'var(--text3)',
        }}>
          <Users size={32} style={{ margin: '0 auto 10px', display: 'block' }} />
          <div style={{ fontSize: 14, fontWeight: 700 }}>No referrals in this category.</div>
        </div>
      ) : (
        <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid var(--border)' }}>
                {['Date', 'Referral Code', 'Referred Customer', 'Status', 'Credits Owed', ''].map(h => (
                  <th key={h} style={{
                    padding: '10px 14px', textAlign: 'left',
                    fontSize: 10, fontWeight: 800, color: 'var(--text3)',
                    textTransform: 'uppercase', letterSpacing: '0.06em',
                  }}>
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filtered.map((r, i) => (
                <tr key={r.id} style={{ borderBottom: i < filtered.length - 1 ? '1px solid var(--border)' : 'none' }}>
                  <td style={{ padding: '12px 14px', fontSize: 12, color: 'var(--text3)', fontFamily: 'JetBrains Mono, monospace' }}>
                    {fmtDate(r.created_at)}
                  </td>
                  <td style={{ padding: '12px 14px' }}>
                    <span style={{
                      fontFamily: 'JetBrains Mono, monospace', fontSize: 12,
                      color: 'var(--accent)', fontWeight: 700,
                    }}>
                      {r.referral_code || '—'}
                    </span>
                  </td>
                  <td style={{ padding: '12px 14px', fontSize: 12, color: 'var(--text2)' }}>
                    {r.referred_customer_id
                      ? <span style={{ fontFamily: 'JetBrains Mono, monospace' }}>{r.referred_customer_id.slice(0, 8)}…</span>
                      : <span style={{ color: 'var(--text3)' }}>—</span>}
                  </td>
                  <td style={{ padding: '12px 14px' }}>
                    <StatusPill status={r.status} />
                  </td>
                  <td style={{ padding: '12px 14px' }}>
                    {(r.status === 'converted' || r.status === 'pending_payout') && (
                      <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 13, fontWeight: 700, color: 'var(--amber)' }}>
                        {fmt(r.commission_amount || 0)}
                      </span>
                    )}
                    {r.status === 'paid' && (
                      <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 13, fontWeight: 700, color: 'var(--green)' }}>
                        {fmt(r.commission_amount || 0)}
                      </span>
                    )}
                    {(r.status !== 'converted' && r.status !== 'pending_payout' && r.status !== 'paid') && (
                      <span style={{ color: 'var(--text3)', fontSize: 12 }}>—</span>
                    )}
                  </td>
                  <td style={{ padding: '12px 14px' }}>
                    {(r.status === 'converted' || r.status === 'pending_payout') && (
                      <button
                        onClick={() => handleMarkPaid(r.id)}
                        disabled={updating === r.id}
                        style={{
                          padding: '4px 12px', borderRadius: 6, border: '1px solid rgba(139,92,246,0.3)',
                          background: 'rgba(139,92,246,0.08)', color: '#8b5cf6',
                          fontSize: 11, fontWeight: 700, cursor: 'pointer',
                          opacity: updating === r.id ? 0.5 : 1,
                        }}
                      >
                        {updating === r.id ? '...' : 'Mark Paid'}
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Credits owed summary */}
      {totalOwed > 0 && (
        <div style={{
          marginTop: 16, padding: '12px 16px',
          background: 'rgba(245,158,11,0.06)',
          border: '1px solid rgba(245,158,11,0.2)',
          borderRadius: 10, fontSize: 13,
          display: 'flex', alignItems: 'center', gap: 8,
        }}>
          <DollarSign size={14} style={{ color: 'var(--amber)' }} />
          <span style={{ color: 'var(--text2)' }}>
            Total referral credits owed:{' '}
            <strong style={{ color: 'var(--amber)', fontFamily: 'JetBrains Mono, monospace' }}>{fmt(totalOwed)}</strong>
          </span>
        </div>
      )}
    </div>
  )
}
